### ISSUE TITLE
pod or container config file without metadata will crash containerd

### ISSUE THREAD

**Issue by teawater** [containerd/cri#1009]
```
root@teawater-virtual-machine:~/vmshare/m# cat p.json
{
  "log_directory": "/tmp",
  "linux": {
  }
}
root@teawater-virtual-machine:~/vmshare/m# crictl runp p.json
DEBU[0000] RunPodSandboxRequest: &RunPodSandboxRequest{Config:&PodSandboxConfig{Metadata:nil,Hostname:,LogDirectory:/tmp,DnsConfig:nil,PortMappings:[],Labels:map[string]string{},Annotations:map[string]string{},Linux:&LinuxPodSandboxConfig{CgroupParent:,SecurityContext:nil,Sysctls:map[string]string{},},},}
2018/12/25 13:29:40 transport: http2Client.notifyError got notified that the client transport was broken EOF.
2018/12/25 13:29:40 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix /var/run/containerd/containerd.sock: connect: connection refused"; Reconnecting to {/var/run/containerd/containerd.sock <nil>}
DEBU[0000] RunPodSandboxResponse: nil
FATA[0000] run pod sandbox failed: rpc error: code = Internal desc = transport is closing

INFO[2018-12-25T13:29:40.769578744+08:00] RunPodSandbox with config &PodSandboxConfig{Metadata:nil,Hostname:,LogDirectory:/tmp,DnsConfig:nil,PortMappings:[],Labels:map[string]string{},Annotations:map[string]string{},Linux:&LinuxPodSandboxConfig{CgroupParent:,SecurityContext:nil,Sysctls:map[string]string{},},}
INFO[2018-12-25T13:29:40.769784271+08:00] RunPodSandbox for nil returns sandbox id ""
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x55e8c49f6c21]

goroutine 53 [running]:
github.com/containerd/containerd/vendor/github.com/containerd/cri/pkg/server.makeSandboxName(0x0, 0x40, 0x101000000000073)
	/home/teawater/gopath/src/github.com/containerd/containerd/vendor/github.com/containerd/cri/pkg/server/helpers.go:143 +0x41
github.com/containerd/containerd/vendor/github.com/containerd/cri/pkg/server.(*criService).RunPodSandbox(0xc00042cb40, 0x55e8c5385b20, 0xc000648300, 0xc00019af00, 0x0, 0x0, 0x0)
	/home/teawater/gopath/src/github.com/containerd/containerd/vendor/github.com/containerd/cri/pkg/server/sandbox_run.go:59 +0xa2
github.com/containerd/containerd/vendor/github.com/containerd/cri/pkg/server.(*instrumentedService).RunPodSandbox(0xc0000b2638, 0x55e8c5385b20, 0xc000648240, 0xc00019af00, 0x0, 0x0, 0x0)
	/home/teawater/gopath/src/github.com/containerd/containerd/vendor/github.com/containerd/cri/pkg/server/instrumented_service.go:63 +0x13b
github.com/containerd/containerd/vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/runtime/v1alpha2._RuntimeService_RunPodSandbox_Handler.func1(0x55e8c5385b20, 0xc000648240, 0x55e8c52c2260, 0xc00019af00, 0xc00023e0f0, 0x55e8c51c4ba0, 0x55e8c5e2c310, 0xc0006d6aa0)
	/home/teawater/gopath/src/github.com/containerd/containerd/vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/runtime/v1alpha2/api.pb.go:4172 +0x8b
github.com/containerd/containerd/vendor/github.com/grpc-ecosystem/go-grpc-prometheus.UnaryServerInterceptor(0x55e8c5385b20, 0xc000648240, 0x55e8c52c2260, 0xc00019af00, 0xc00019af80, 0xc00019afa0, 0x55e8c51c4ba0, 0x55e8c5e2c310, 0x55e8c531dc60, 0xc00034a0f0)
	/home/teawater/gopath/src/github.com/containerd/containerd/vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server.go:29 +0xa6
github.com/containerd/containerd/vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/runtime/v1alpha2._RuntimeService_RunPodSandbox_Handler(0x55e8c5333f00, 0xc0000b2638, 0x55e8c5385b20, 0xc000648240, 0xc0003760e0, 0x55e8c53607f8, 0x0, 0x0, 0x0, 0x0)
	/home/teawater/gopath/src/github.com/containerd/containerd/vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/runtime/v1alpha2/api.pb.go:4174 +0x15a
github.com/containerd/containerd/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000380fc0, 0x55e8c538fea0, 0xc000148000, 0xc00034a0f0, 0xc000290930, 0x55e8c5dbf3d8, 0x0, 0x0, 0x0)
	/home/teawater/gopath/src/github.com/containerd/containerd/vendor/google.golang.org/grpc/server.go:1011 +0x4cf
github.com/containerd/containerd/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000380fc0, 0x55e8c538fea0, 0xc000148000, 0xc00034a0f0, 0x0)
	/home/teawater/gopath/src/github.com/containerd/containerd/vendor/google.golang.org/grpc/server.go:1249 +0x130a
github.com/containerd/containerd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00003e7c0, 0xc000380fc0, 0x55e8c538fea0, 0xc000148000, 0xc00034a0f0)
	/home/teawater/gopath/src/github.com/containerd/containerd/vendor/google.golang.org/grpc/server.go:680 +0xa1
created by github.com/containerd/containerd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/home/teawater/gopath/src/github.com/containerd/containerd/vendor/google.golang.org/grpc/server.go:678 +0xa3
```

**Comment by Random-Liu** [comment]
@teawater Thanks for the bug report!

**Comment by Random-Liu** [comment]
Let's keep this open for now, we need an integration test for this case.
